service: ssr-react-swapi-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 150

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true
  data:
    handler: data/server.handler
    events:
      - http: ANY data
        cors: true
      - http: 'ANY data/{proxy+}'
        cors: true
    vpc:
      securityGroupIds:
        - sg-093754acc09e620b8
      subnetIds:
        - subnet-5b87e411
        - subnet-34f12f53
        - subnet-d79209d8
        - subnet-9f6488a1
        - subnet-48924d14
        - subnet-74a47d5a
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
        Resource: "*"
    environment:
      PGRDS_CONN: ${ssm:ssrReactSwapiRdsConn}
      NODE_ENV: ${opt:node_env}

plugins:
  - serverless-domain-manager
  - serverless-offline

package:
  include:
    - server
    - data/**
    - env

custom:
  customDomain:
    domainName: swguesswho.kalalau-cantrell.me
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.kalalau-cantrell.me'